### PR TITLE
remove use of empty TROLLTECH symbol in environment setup

### LINKED ISSUE #58: Why is TROLLTECH used here?
On this line: https://github.com/caqtdm/caqtdm/blob/9abca43e8b4aa3fbf0d9aa766f5b0a136c3d1027/caQtDM_Env#L62

Since it is used inside an `if ...` block that has already determined the symbol is empty, the line will include `:/binQt:` in the `QTDM_RPATH`.  While it causes no harm, it is not necessary.

Is there some other reason to keep `:$TROLLTECH/binQt` as part of this line?

### PR DESCRIPTION
**Pull request by prjemian**
- close #58

### CODE REVIEW

**Comment by prjemian** [comment]
@HelgeBrands : Only this one change for now.

**Comment by prjemian** [comment]
If I understand, this PR will not be needed then since you have made the change locally.  Correct?

**Comment by HelgeBrands** [comment]
Yesyou are right. It is now in the Release branch already committed!

**Comment by prjemian** [comment]
No need for this PR now.

**Comment by prjemian** [comment]
@HelgeBrands Thanks!

**Pull request closed without merging**
