### PR TITLE
solving problem with too wide controls in pep screens

### PR DESCRIPTION
**Pull request by tomazsustar**
https://tracker.psi.ch/jira/browse/COSYLAB-548

### CODE REVIEW

**Comment by AntonMezger** [comment]
I will first, at the end of the week, carefully test if you did not produce any side effects in other screens.

**Comment by AntonMezger** [comment]
I use another method to know if one is in the designer or not. My way does not break binary compatibility, while no variables and change of methods are involved. I will modify it therefore my way!

**Comment by tomazsustar** [comment]
Sure, if there is a better solution, go ahead. Would you mind sharing how do you it?

**Comment by AntonMezger** [comment]
Hi,

You took off the minimalwidth of calineedit. This has an impact on several screens and I will keep the minimalwidth of 100 therefore.

Best regards

Anton

**Comment by AntonMezger** [comment]
I modified cachoice in order not to expand itself unnecessary. I also modified the pep implementation to accept a comment font size (-comsize) and I added an option –minwidth in order to specify the minimal width of 100. You may set this option in formRead to increase or decrease the minimum column width.

See attachment

**Pull request closed without merging**
